"""Add timecards table

Revision ID: 064b9aca021b
Revises: f9d56d28b213
Create Date: 2024-08-19 04:54:28.331173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064b9aca021b'
down_revision: Union[str, None] = 'f9d56d28b213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'zip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'marital_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'comp_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'general_department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'department_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'hourly_salary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'pay_type_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'pay_rate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'pay_rate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'pay_type_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'hourly_salary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'department_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'general_department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'comp_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'marital_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'zip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
