"""Add employee_coding and receipt_image_path to credit_card_transactions

Revision ID: 0dd46ff91dae
Revises: 684a9f862d38
Create Date: 2024-08-25 09:16:11.994071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd46ff91dae'
down_revision: Union[str, None] = '684a9f862d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_transactions', sa.Column('employee_coding', sa.Text(), nullable=True))
    op.add_column('credit_card_transactions', sa.Column('receipt_image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_transactions', 'receipt_image_path')
    op.drop_column('credit_card_transactions', 'employee_coding')
    # ### end Alembic commands ###
