"""Add Receipt model

Revision ID: 133e60979484
Revises: 064b9aca021b
Create Date: 2024-08-23 13:01:25.874060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133e60979484'
down_revision: Union[str, None] = '064b9aca021b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_card_transactions_id'), 'credit_card_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_card_transactions_id'), table_name='credit_card_transactions')
    # ### end Alembic commands ###
