"""Fix relationships for receipts and transactions

Revision ID: 1d1fc4c8820d
Revises: 0dd46ff91dae
Create Date: 2024-08-25 09:26:08.728958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1fc4c8820d'
down_revision: Union[str, None] = '0dd46ff91dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_transactions', 'receipt_image_path')
    op.drop_column('credit_card_transactions', 'employee_coding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_transactions', sa.Column('employee_coding', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('credit_card_transactions', sa.Column('receipt_image_path', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
