"""Add admin role to UserRole enum

Revision ID: 22dd35b8089a
Revises: c065018a1229
Create Date: 2024-08-18 14:20:37.255166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dd35b8089a'
down_revision: Union[str, None] = 'c065018a1229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_column('daily_time_reports', 'phase_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_time_reports', sa.Column('phase_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('employees',
    sa.Column('emp_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('town', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('comp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('general_department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hourly_salary', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pay_type_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pay_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('emp_code', name='employees_pkey')
    )
    # ### end Alembic commands ###
