"""Create employees table

Revision ID: 237df7db66bf
Revises: ab4f5202151e
Create Date: 2024-08-18 20:58:50.927508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237df7db66bf'
down_revision: Union[str, None] = 'ab4f5202151e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('comp_code', sa.String(), nullable=False),
    sa.Column('general_department', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('department_code', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hourly_salary', sa.String(), nullable=False),
    sa.Column('pay_type_code', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pay_rate', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('emp_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=False)
    op.drop_index('ix_equipment_equipment_number', table_name='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_equipment_equipment_number', 'equipment', ['equipment_number'], unique=False)
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
