"""Add employee_coding and receipt_image_path to credit_card_transactions

Revision ID: 3fac4a9736f6
Revises: 1d1fc4c8820d
Create Date: 2024-08-25 10:09:41.354285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fac4a9736f6'
down_revision: Union[str, None] = '1d1fc4c8820d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_transactions', sa.Column('employee_coding', sa.Text(), nullable=True))
    op.add_column('credit_card_transactions', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('employee_coding', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('receipts', 'emp_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('emp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('receipts', 'image_path')
    op.drop_column('receipts', 'employee_coding')
    op.drop_column('credit_card_transactions', 'image_path')
    op.drop_column('credit_card_transactions', 'employee_coding')
    # ### end Alembic commands ###
