"""Add coding field to receipts

Revision ID: 50abca131d4e
Revises: 133e60979484
Create Date: 2024-08-25 06:41:21.430454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50abca131d4e'
down_revision: Union[str, None] = '133e60979484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('coding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'coding')
    # ### end Alembic commands ###
