"""Add emp_code field to receipts

Revision ID: 684a9f862d38
Revises: 50abca131d4e
Create Date: 2024-08-25 08:07:25.290607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684a9f862d38'
down_revision: Union[str, None] = '50abca131d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('emp_code', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipts', 'credit_card_transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'transaction_id')
    op.drop_column('receipts', 'emp_code')
    # ### end Alembic commands ###
