"""Remove weight_class from equipment

Revision ID: a6742cedc11d
Revises: d034f81c33a2
Create Date: 2024-08-18 20:10:05.452250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6742cedc11d'
down_revision: Union[str, None] = 'd034f81c33a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_number', sa.String(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('equipment_make', sa.String(), nullable=False),
    sa.Column('vin_model_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_number'), 'equipment', ['equipment_number'], unique=False)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_number'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
