"""Allow nulls in pay_type_code column

Revision ID: b5336b408180
Revises: 237df7db66bf
Create Date: 2024-08-18 21:07:18.614664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5336b408180'
down_revision: Union[str, None] = '237df7db66bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pay_type_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pay_type_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
