"""Allow nulls in pay_type_code column

Revision ID: f9d56d28b213
Revises: b5336b408180
Create Date: 2024-08-18 21:08:33.578543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d56d28b213'
down_revision: Union[str, None] = 'b5336b408180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('comp_code', sa.String(), nullable=False),
    sa.Column('general_department', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('department_code', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hourly_salary', sa.String(), nullable=False),
    sa.Column('pay_type_code', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pay_rate', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('emp_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
